[workspace]
members = [
  "validate",
  "validate/remote",
  "sass",
  "ptx",
  "cuda/cudart",
  "profile",
  "playground",
  "playground/sys",
  "exec",
  "exec/derive",
  "stats",
  "benchmarks",
  "accelsim",
  "accelsim/trace",
  "accelsim/sim",
  "utils",
  "trace",
  "trace/invoke",
  "trace/model",
  "xtask", "diff",
]

[profile.dev]
opt-level = 0 # no optimizations
debug = 2 # full debug info

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# link time optimization takes too long
lto = false
opt-level = 3
debug = true
# warning: debug assertions negatively impact the performance of accelsim and play
debug-assertions = false

[profile.bench]
lto = false
# warning: debug assertions negatively impact the performance of accelsim and play
debug-assertions = false
# codegen-units = 10
opt-level = 3
debug = true

[package]
name = "gpucachesim"
version = "0.1.0"
edition = "2021"
publish = false

[features]
# default = ["detailed-stats", "parking_lot", "parallel", "deadlock_detection"]
# default = ["detailed-stats", "parking_lot", "parallel", "jemalloc"]
# default = ["parking_lot", "parallel", "jemalloc", "timings"]
default = ["parking_lot", "parallel", "jemalloc"]
# default = ["parallel"]
# default = ["parallel", "timings"]
# default = ["parking_lot", "parallel", "deadlock_detection"]
deadlock_detection = ["parking_lot/deadlock_detection"]
jemalloc = ["dep:tikv-jemallocator"]
timings = []
detailed-stats = ["stats/detailed-stats"]
parallel = ["dep:rayon"]
parking_lot = []
python = ["dep:pyo3"]
local-data = []

[package.metadata.cargo-feature-combinations]
denylist = ["default", "local-data"]

[[bench]]
name = "vectoradd"
harness = false
required-features =  ["parallel"] 

[dependencies]
color-eyre = "0"
human_bytes = "0"
console = "0"
thiserror = "1"
nvbit-model = "0"
nvbit-io = "0"
regex = "1"
itertools = "0"
indexmap = { version = "2", features = ["serde"] }
serde_yaml = "0"
csv = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"
log = "0"
env_logger = "0"
once_cell = "1"
bitvec = "1"
strum = { version = "0", features = ["derive"] }
phf = { version = "0.11.1", features = ["macros"] }
rangemap = "1"
ndarray = "0"
smallvec = { version = "1", features = ["const_generics"] }
vec-collections = "0"
lockfree = "0" # no used right now, used crossbeam for now

# serde_json_merge = "0"

# synchronization
flume = "0"
crossbeam = "0"
num_cpus = "1"
parking_lot = { version = "0", features = ["deadlock_detection"] }

# tracing
tracing = "0"
tracing-subscriber = "0"
tracing-chrome = "0"

# parallel simulation
rayon = { version = "1", optional = true }

trace-model = { path = "./trace/model" }
stats = { path = "./stats" }
utils = { path = "./utils" }

# exec driven (todo: make this a feature)
exec = { path = "./exec" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0", optional = true }

[dependencies.pyo3]
version = "0"
features = ["extension-module"]
optional = true

[dev-dependencies]
pretty_assertions_sorted = "1"
cxx = "1"
paste = "1"
num-traits = "0"
diff = { path = "./diff" }
criterion = { version = "0.5", features = ["async_tokio"] }

# sanity check stats against playground
playground = { path = "./playground" }
accelsim = { path = "./accelsim" }
accelsim-sim = { path = "./accelsim/sim" }
validate = { path = "./validate" }

# testing if ffi works in async contexts
tokio = { version = "1", features = ["full"] }
async-process = "1"
futures = "0.3"
