[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["cuda"]
cuda = ["dep:rustacuda", "dep:cuda-driver-sys"]

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[package.metadata.cargo-feature-combinations.matrix]
need_cuda = true
need_accelsim_build_dependencies = true

[dependencies]
color-eyre = "0"
console = "0"
dialoguer = "0"
duct = "0"
once_cell = "1"
regex = "1"
glob = "0"
difflib = "0"
diff = { path = "../diff" }
indicatif = "0"
num_cpus = "1"
chrono = "0"
rayon = "1"
itertools = "0"
bitvec = "1"
common-path = "1"
walkdir = "2"
log = "0"
env_logger = "0"

serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0"
csv = "1"
rmp-serde = "1"
indexmap = { version = "2", features = ["serde"] }
strum = { version = "0", features = ["derive"] }

clap = { version = "4", features = ["derive"] }

utils = { path = "../utils" }
gpucachesim = { path = "../" }
accelsim = { path = "../accelsim" }
trace-model = { path = "../trace/model" }
validate = { path = "../validate" }

# optional: cuda
rustacuda = { version = "0", optional = true }
cuda-driver-sys = { version = "0", optional = true }
