[package]
name = "accelsim"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[[bin]]
name = "accelsim-parse"

[features]
default  = ["local-data"]
local-data = []

[package.metadata.cargo-feature-combinations]
denylist = ["default", "local-data"]

[dependencies]
color-eyre = "0"
duct = "0"
itertools = "0"
regex = "1"
once_cell = "1"
log = "0"
env_logger = "0"
ndarray = { version = "0", features = ["serde"] }
indexmap = { version = "2", features = ["serde"] }
rev_buf_reader = "0"
duration-string = "0"
clap = { version = "4", features = [ "derive" ] }

# trace compat
serde = { version = "1", features = ["derive"] }
rmp-serde = "1"
bitvec = "1"
num-traits = "0"
serde_json = "1"
nvbit-model = "0"
trace-model = { path = "../trace/model" }
utils = { path = "../utils" }

# stats conversion
stats = { path = "../stats" }
strum = { version = "0", features = ["derive"] }

[dev-dependencies]
similar-asserts = "1"
indoc = "2"
