[package]
name = "validate"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["remote", "parallel", "cuda"]
cuda = ["dep:rustacuda", "dep:cuda-driver-sys"]
timings = ["gpucachesim/timings"]
parallel = ["gpucachesim/parallel"]
remote = ["dep:remote"]

[package.metadata.cargo-feature-combinations]
denylist = ["default", "cuda"]

[package.metadata.cargo-feature-combinations.matrix]
need_cuda = true
need_accelsim_build_dependencies = true

[dependencies]
thiserror = "1"
color-eyre = "0"
async-trait = "0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_path_to_error = "0"
csv = "1"
serde_json = { version = "1", features = ["preserve_order"] }
rmp-serde = "1"
serde_yaml = "0"
serde_json_merge = "0"
try-partialord = "0"
duration-string = { version = "0", features = ["serde"] }
log = "0"
dotenv = "0"
env_logger = "0"
handlebars = "4"
shell-words = "1"
indexmap = { version = "2", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
argmap = "1"
indicatif = "0"
futures = "0.3"
num_cpus = "1"
console = "0"
pathdiff = "0"
tempfile = "3"
smart-default = "0"
chrono = "0"
itertools = "0"
human_bytes = "0"
once_cell = "1"
async-process = "1"
strum = { version = "0", features = ["derive"] }

utils = { path = "../utils" }

# trace
invoke-trace = { path = "../trace/invoke" }
trace-model = { path = "../trace/model" }

# profile
profile = { path = "../profile" }

# accelsim trace
accelsim-trace = { path = "../accelsim/trace" }

# accelsim simulate
accelsim-sim = { path = "../accelsim/sim" }
accelsim = { path = "../accelsim" }

# playground simulate
playground = { path = "../playground" }

# simulate
gpucachesim = { path = "../" }
stats = { path = "../stats" }

# benchmarks
gpucachesim-benchmarks = { path = "../benchmarks" }

# optional: remote
remote = { path = "./remote", optional = true }

# optional: cuda
rustacuda = { version = "0", optional = true }
cuda-driver-sys = { version = "0", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0"

# this does not help unfortunately
# [profile.dev.package.serde_yaml]
# opt-level = 3
#
# [profile.dev.package.serde]
# opt-level = 3
#
# [profile.dev.package.serde_json]
# opt-level = 3

[dev-dependencies]
pretty_assertions_sorted = "1"
