# [target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[alias]
xtask = "run --package xtask --"
validate = "run --release --package validate --"
trace = "run --release --package invoke-trace --"
sim = "run --release --"
accelsim-trace = "run --release --package accelsim-trace --"
accelsim-sim = "run --release --package accelsim-sim --"
playground-sim = "run --release --package playground-sim --"
pchase = "run --release --package gpucachesim-benchmarks --bin pchase --"

t = "test -- --test-threads=1"
tt = "test --release -- --test-threads=1"

tv = "test -- --nocapture --test-threads=1"
ttv = "test --release -- --nocapture --test-threads=1"
