[package]
name = "ptxbison"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = [ "derive" ] }
color-eyre = "0"

[build-dependencies]
color-eyre = "0"
duct = "0"
bindgen = "0"
cc = { version = "1", features = [] }
