name: feature-matrix
on:
  workflow_call:
    outputs:
      matrix:
        description: "the feature matrix"
        value: ${{ jobs.matrix.outputs.matrix }}
jobs:
  matrix:
    name: Generate feature matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: romnn/cargo-feature-combinations@main
      - name: Compute feature matrix
        id: compute-matrix
        run: |
          cargo fc matrix --pretty
          matrix="$(cargo fc matrix)"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
